### ISSUE TITLE
Event handler presenter.Completed not hit

### ISSUE THREAD

**Issue by SudhersonV** [snickler/Samples#1]
I downloaded your code and had t upgrade the packages, the event handler presenter.Completed += Presenter_Completed; is never hit. Please can you check with the latest Xamarin Forms packages?

**Comment by snickler** [comment]
@SudhersonV - The code for this was made with those specific Xamarin.Auth versions. Unfortunately, Xamarin.Auth isn't supported anymore but Xamarin.Essentials now has a WebAuthenticator class based off of Xamarin.Auth. I will have to do a follow up post / code update using the newer packages.

**Comment by SudhersonV** [comment]
@snickler, thank you for your response. The problem was with my code, I found a solution to use with Net Standard using using System.Security.Cryptography.Algorithms  nuget package.


        private string CreateCodeVerifier()
        {
            var rnd = new Random();
            var codeBytes = new Byte[64];
            rnd.NextBytes(codeBytes);
            return Convert.ToBase64String(codeBytes).Replace("+", "-").Replace("/", "_").Replace("=", "");
        }        

        private string CreateChallenge(string code)
        {
            var codeVerifier = code;
            var sha256 = new SHA256CryptoServiceProvider();            
            var challengeByteArray = sha256.ComputeHash(Encoding.UTF8.GetBytes(codeVerifier));
            byte[] challengeBytes = new byte[challengeByteArray.Length];
            sha256.TransformBlock(challengeByteArray, 0, challengeByteArray.Length, challengeBytes, 0);
            return Convert.ToBase64String(challengeBytes).Replace("+", "-").Replace("/", "_").Replace("=", "");
        }

I will tread the path of using Xamarin.Essentials.

**Comment by snickler** [comment]
Awesome, great to know!
